### ISSUE TITLE
Uncaught TypeError: fs.readFileSync is not a function

### ISSUE THREAD

**Issue by infacq** [sleepycat/mapboxgl-webpack-example#3]
This error has trouble for two days now. Do you mind to check my setup [here](http://stackoverflow.com/questions/37608118/uncaught-typeerror-fs-readfilesync-is-not-a-function)

**Comment by sleepycat** [comment]
Take a look at [brfs](https://github.com/substack/brfs). It looks like the fs.readFileSync calls brfs replaces got moved. You can fix it like this:

``` javascript
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          presets: ['es2015', 'stage-0']
        }
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
        loader: 'transform/cacheable?brfs'
      },
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'node_modules/mapbox-gl-shaders/index.js'),
        loader: 'transform/cacheable?brfs'
      }
    ]
  },
};

```

The deeper problem is those paths are too specific so it will probably break again. The loader suggested in one of the answers to your question seems like a better solution:

``` javascript
    loaders: [
      {
        test: /mapbox-gl.+\.js$/,
        loader: 'transform/cacheable?brfs'
      }
    ]
```

Does that solve it?

**Comment by KendallPark** [comment]
It solved it for me.

**Comment by sleepycat** [comment]
This seems to be addressed, so I'll close it. Let me know if we need to reopen it.

**Comment by infacq** [comment]
thank you
